# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
import numpy as np
from numpy import *

In [2]:
arr = np.array([[1,2,3,4,5],[2,4,6,8,10]],int)

In [3]:
arr

array([[ 1,  2,  3,  4,  5],
       [ 2,  4,  6,  8, 10]])

In [4]:
type(arr)

numpy.ndarray

In [5]:
#transpse
arr.T

array([[ 1,  2],
       [ 2,  4],
       [ 3,  6],
       [ 4,  8],
       [ 5, 10]])

In [6]:
arr[0:1]

array([[1, 2, 3, 4, 5]])

In [7]:
arr>10

array([[False, False, False, False, False],
       [False, False, False, False, False]])

In [8]:
arr.shape

(2, 5)

In [9]:
arr.size

10

In [10]:
arr.dtype

dtype('int32')

In [11]:
arr<10

array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True, False]])

In [12]:
where(arr%2!=0,arr,0) 

array([[1, 0, 3, 0, 5],
       [0, 0, 0, 0, 0]])

In [13]:
#we can also use the arange method and then reshape the array into the desired matrix
d2 = np.arange(start = 9, stop = 0, step = -1)
d2 = d2.reshape(3,3)

In [14]:
d2

array([[9, 8, 7],
       [6, 5, 4],
       [3, 2, 1]])

In [15]:
# Adds the constant to each element of the array.
d2 + 1

array([[10,  9,  8],
       [ 7,  6,  5],
       [ 4,  3,  2]])

In [16]:
# Returns mean of the elements of array.
d2.mean()

5.0

In [57]:
lp = np.linspace(0,20,6)

In [58]:
lp

array([ 0.,  4.,  8., 12., 16., 20.])

In [59]:
# 5x5 array of 0 with 1 on diagonal (Identity matrix)
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [60]:
 # 2x3 array with all values 8
np.full((2,3),8)

array([[8, 8, 8],
       [8, 8, 8]])

In [19]:
np.cos(np.pi)

-1.0

In [20]:
np.sqrt(81.1)

9.00555384193554

In [21]:
np.log(np.exp(5.2))

5.2

In [22]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)

In [23]:
vec2

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [24]:
vec3 = np.arange(3,21,6)

In [25]:
vec3

array([ 3,  9, 15])

In [26]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [27]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [28]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [29]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [30]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.59559304 0.22220342 0.12787051 0.69320645 0.84810147]
 [0.53952948 0.30822766 0.14995893 0.8736937  0.45616715]
 [0.96017356 0.46808799 0.25185454 0.36232907 0.16971996]
 [0.06624064 0.72990069 0.11185028 0.40726834 0.53033297]
 [0.1170142  0.04330027 0.27407198 0.45303816 0.48738825]]

[[ 1.36413317 -0.91854407 -0.01737141 -0.37241814  0.1939815 ]
 [ 0.72798862  0.73127385 -1.16812128 -1.44215804  1.522981  ]
 [ 0.49613574 -0.07461444  0.42902284 -0.95615609  2.21064991]
 [ 0.93142495  0.7481022   0.07240928 -1.15976102 -1.01927743]
 [-0.75564431 -1.00893731 -0.06893155 -0.26521186  0.80359658]
 [ 1.61040148  0.12236433 -1.03733869 -0.292318   -0.00811614]
 [-0.29589636  0.80182963 -0.12167325  0.94470546  0.75764065]
 [-1.04466882  0.00452903  0.10635619  2.19454379  1.88665051]
 [-1.12798944 -1.18773131 -0.24095546  0.81747617 -1.95892565]
 [-2.14683676 -0.73097672 -0.45614487  0.6961071  -0.7279252 ]]


In [31]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4098849086087166
1.011352022071101


In [32]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.043300273346935314
2.2106499075354393


In [33]:
# break here for next video!

In [34]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 2.30713799  0.08645967 -0.82625317  0.16231963 -1.40820745 -0.65876501
 -0.76055059 -0.28718882  0.36597923  0.37653586 -1.45325193 -0.06319211
  1.01134751  2.10234578  0.02276088 -0.88066349  0.38198651 -1.70620476
  1.40707189]
-0.7605505915837529


In [35]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[-1.40820745 -0.65876501 -0.76055059 -0.28718882  0.36597923]


In [36]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 2.30713799  0.16231963 -0.76055059  0.37653586  1.01134751]


In [37]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.59559304 0.22220342 0.12787051 0.69320645 0.84810147]
 [0.53952948 0.30822766 0.14995893 0.8736937  0.45616715]
 [0.96017356 0.46808799 0.25185454 0.36232907 0.16971996]
 [0.06624064 0.72990069 0.11185028 0.40726834 0.53033297]
 [0.1170142  0.04330027 0.27407198 0.45303816 0.48738825]]
0.14995893268813765
0.14995893268813765


In [38]:
print(rand_mat[0:2,1:3])

[[0.22220342 0.12787051]
 [0.30822766 0.14995893]]


In [39]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 2.30713799  0.08645967 -0.82625317  0.16231963 -1.40820745 -0.65876501
 -0.76055059 -0.28718882  0.36597923  0.37653586 -1.45325193 -0.06319211
  1.01134751  2.10234578  0.02276088 -0.88066349  0.38198651 -1.70620476
  1.40707189]

[ 2.30713799  0.08645967 -0.82625317  4.          4.         -0.65876501
 -0.76055059 -0.28718882  0.36597923  0.37653586 -1.45325193 -0.06319211
  1.01134751  2.10234578  0.02276088 -0.88066349  0.38198651 -1.70620476
  1.40707189]

[ 2.30713799  0.08645967 -0.82625317  1.          2.         -0.65876501
 -0.76055059 -0.28718882  0.36597923  0.37653586 -1.45325193 -0.06319211
  1.01134751  2.10234578  0.02276088 -0.88066349  0.38198651 -1.70620476
  1.40707189]


In [40]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.59559304 0.22220342 0.12787051 0.69320645 0.84810147]
 [0.53952948 0.30822766 0.14995893 0.8736937  0.45616715]
 [0.96017356 0.46808799 0.25185454 0.36232907 0.16971996]
 [0.06624064 0.72990069 0.11185028 0.40726834 0.53033297]
 [0.1170142  0.04330027 0.27407198 0.45303816 0.48738825]]

[[0.59559304 0.22220342 0.12787051 0.69320645 0.84810147]
 [0.53952948 0.30822766 0.14995893 0.         0.        ]
 [0.96017356 0.46808799 0.25185454 0.         0.        ]
 [0.06624064 0.72990069 0.11185028 0.40726834 0.53033297]
 [0.1170142  0.04330027 0.27407198 0.45303816 0.48738825]]


In [41]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.59559304 0.22220342 0.12787051]
 [0.53952948 0.30822766 0.14995893]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [42]:
print(rand_mat)

[[3.         3.         3.         0.69320645 0.84810147]
 [3.         3.         3.         0.         0.        ]
 [0.96017356 0.46808799 0.25185454 0.         0.        ]
 [0.06624064 0.72990069 0.11185028 0.40726834 0.53033297]
 [0.1170142  0.04330027 0.27407198 0.45303816 0.48738825]]


In [43]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.69320645 0.84810147]
 [3.         3.         3.         0.         0.        ]
 [0.96017356 0.46808799 0.25185454 0.         0.        ]
 [0.06624064 0.72990069 0.11185028 0.40726834 0.53033297]
 [0.1170142  0.04330027 0.27407198 0.45303816 0.48738825]]


In [44]:
# break here for next video

In [45]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-2.45752485  0.62070023 -0.80344797 -0.68903295  0.94728621 -0.31313704
 -1.37192366 -0.39473577 -0.96078293 -1.1041482  -0.43537795 -0.1733273
 -1.17012309 -1.506668    0.57943234]
[False  True False False  True False False False False False False False
 False False  True]
[0.62070023 0.94728621 0.57943234]


In [46]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 1.36413317 -0.91854407 -0.01737141 -0.37241814  0.1939815 ]
 [ 0.72798862  0.73127385 -1.16812128 -1.44215804  1.522981  ]
 [ 0.49613574 -0.07461444  0.42902284 -0.95615609  2.21064991]
 [ 0.93142495  0.7481022   0.07240928 -1.15976102 -1.01927743]
 [-0.75564431 -1.00893731 -0.06893155 -0.26521186  0.80359658]
 [ 1.61040148  0.12236433 -1.03733869 -0.292318   -0.00811614]
 [-0.29589636  0.80182963 -0.12167325  0.94470546  0.75764065]
 [-1.04466882  0.00452903  0.10635619  2.19454379  1.88665051]
 [-1.12798944 -1.18773131 -0.24095546  0.81747617 -1.95892565]
 [-2.14683676 -0.73097672 -0.45614487  0.6961071  -0.7279252 ]]
[1.36413317 0.1939815  0.72798862 0.73127385 1.522981   0.49613574
 0.42902284 2.21064991 0.93142495 0.7481022  0.07240928 0.80359658
 1.61040148 0.12236433 0.80182963 0.94470546 0.75764065 0.00452903
 0.10635619 2.19454379 1.88665051 0.81747617 0.6961071 ]


In [47]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-2.45752485  0.62070023 -0.80344797 -0.68903295  0.94728621 -0.31313704
 -1.37192366 -0.39473577 -0.96078293 -1.1041482  -0.43537795 -0.1733273
 -1.17012309 -1.506668    0.57943234]

[-2.45752485 -5.         -0.80344797 -0.68903295 -5.         -0.31313704
 -1.37192366 -0.39473577 -0.96078293 -1.1041482  -0.43537795 -0.1733273
 -1.17012309 -1.506668   -5.        ]


In [48]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [49]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [50]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[ 1.36413317 -0.91854407 -0.01737141 -0.37241814  0.1939815 ]
 [ 0.72798862  0.73127385 -1.16812128 -1.44215804  1.522981  ]
 [ 0.49613574 -0.07461444  0.42902284 -0.95615609  2.21064991]
 [ 0.93142495  0.7481022   0.07240928 -1.15976102 -1.01927743]
 [-0.75564431 -1.00893731 -0.06893155 -0.26521186  0.80359658]
 [ 1.61040148  0.12236433 -1.03733869 -0.292318   -0.00811614]
 [-0.29589636  0.80182963 -0.12167325  0.94470546  0.75764065]
 [-1.04466882  0.00452903  0.10635619  2.19454379  1.88665051]
 [-1.12798944 -1.18773131 -0.24095546  0.81747617 -1.95892565]
 [-2.14683676 -0.73097672 -0.45614487  0.6961071  -0.7279252 ]]



In [51]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.69320645 0.84810147]
 [3.         3.         3.         0.         0.        ]
 [0.96017356 0.46808799 0.25185454 0.         0.        ]
 [0.06624064 0.72990069 0.11185028 0.40726834 0.53033297]
 [0.1170142  0.04330027 0.27407198 0.45303816 0.48738825]]

[[ 1.36413317 -0.91854407 -0.01737141 -0.37241814  0.1939815 ]
 [ 0.72798862  0.73127385 -1.16812128 -1.44215804  1.522981  ]
 [ 0.49613574 -0.07461444  0.42902284 -0.95615609  2.21064991]
 [ 0.93142495  0.7481022   0.07240928 -1.15976102 -1.01927743]
 [-0.75564431 -1.00893731 -0.06893155 -0.26521186  0.80359658]
 [ 1.61040148  0.12236433 -1.03733869 -0.292318   -0.00811614]
 [-0.29589636  0.80182963 -0.12167325  0.94470546  0.75764065]
 [-1.04466882  0.00452903  0.10635619  2.19454379  1.88665051]
 [-1.12798944 -1.18773131 -0.24095546  0.81747617 -1.95892565]
 [-2.14683676 -0.73097672 -0.45614487  0.6961071  -0.7279252 ]]
[[3.         3.         3.         0.69320645 0.84810147]
 [3.         3.    

In [52]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.69320645 0.84810147]
 [3.         3.         3.         0.         0.        ]
 [0.96017356 0.46808799 0.25185454 0.         0.        ]
 [0.06624064 0.72990069 0.11185028 0.40726834 0.53033297]
 [0.1170142  0.04330027 0.27407198 0.45303816 0.48738825]]

[[3.         3.         3.         0.69320645 0.84810147]
 [3.         3.         3.         0.         0.        ]
 [0.96017356 0.46808799 0.25185454 0.         0.        ]
 [0.06624064 0.72990069 0.11185028 0.40726834 0.53033297]
 [0.1170142  0.04330027 0.27407198 0.45303816 0.48738825]]
