# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.99576275 0.27231976 0.74169227 0.39475199 0.8699924 ]
 [0.69675455 0.44521794 0.98412739 0.38812475 0.23420812]
 [0.39168536 0.43358234 0.41923536 0.67790156 0.34447072]
 [0.52313917 0.74814067 0.04429527 0.9925114  0.29490404]
 [0.65819841 0.38295219 0.81053361 0.09843601 0.30303452]]

[[ 0.99841174  1.19087221  1.34235363  0.30954263 -1.06662954]
 [ 1.93428128 -0.77297732 -0.69651767 -1.22369038  0.96309001]
 [ 0.3971089  -0.85831336 -1.62717844 -1.18211063 -1.45721847]
 [-0.73282126  0.27232172  0.64640574 -0.24428632  1.44005335]
 [-0.79082655  0.27775554 -0.23358337  0.96002324  2.06955452]
 [-2.24079197  1.45751308 -1.09690368 -1.39318148 -0.31499255]
 [ 0.39067135 -0.01517538 -0.31982344  1.05236168  0.95496651]
 [ 0.21736805  0.70576706  2.07862167 -1.32527305 -1.29273795]
 [ 0.13456735  0.94106121  0.31561565  0.84381792 -0.33350751]
 [-0.06015472 -1.57121527 -0.81940994 -0.25406224  0.3716493 ]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.5258389017476776
1.0489457874838612


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.044295273045275696
2.0786216715636785


In [14]:
# break here for next video!

In [15]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[-2.0424173   0.88785103  0.63323208  0.00891316 -0.87723768  0.68815314
 -0.53173117 -1.0369735   1.48696967 -0.17375567  1.81910838  1.8033512
  1.64270003  0.59631723 -0.17973799 -0.24514122 -0.77995028 -0.04840992
 -0.11230268]
-0.5317311703254035


In [ ]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

In [ ]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

In [ ]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


In [ ]:
print(rand_mat[0:2,1:3])

In [ ]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

In [ ]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

In [ ]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


In [ ]:
print(rand_mat)

In [ ]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


In [ ]:
# break here for next video

In [16]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.56620017 -1.08320021  1.37142501  0.70791682 -1.07411654  1.05777888
  1.0367876   1.56390765  0.48015549  0.43813832  0.36325629 -0.56231393
  0.98987071  0.08255392  0.53088464]
[False False  True  True False  True  True  True  True  True  True False
  True  True  True]
[1.37142501 0.70791682 1.05777888 1.0367876  1.56390765 0.48015549
 0.43813832 0.36325629 0.98987071 0.08255392 0.53088464]


In [17]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[ 0.99841174  1.19087221  1.34235363  0.30954263 -1.06662954]
 [ 1.93428128 -0.77297732 -0.69651767 -1.22369038  0.96309001]
 [ 0.3971089  -0.85831336 -1.62717844 -1.18211063 -1.45721847]
 [-0.73282126  0.27232172  0.64640574 -0.24428632  1.44005335]
 [-0.79082655  0.27775554 -0.23358337  0.96002324  2.06955452]
 [-2.24079197  1.45751308 -1.09690368 -1.39318148 -0.31499255]
 [ 0.39067135 -0.01517538 -0.31982344  1.05236168  0.95496651]
 [ 0.21736805  0.70576706  2.07862167 -1.32527305 -1.29273795]
 [ 0.13456735  0.94106121  0.31561565  0.84381792 -0.33350751]
 [-0.06015472 -1.57121527 -0.81940994 -0.25406224  0.3716493 ]]
[0.99841174 1.19087221 1.34235363 0.30954263 1.93428128 0.96309001
 0.3971089  0.27232172 0.64640574 1.44005335 0.27775554 0.96002324
 2.06955452 1.45751308 0.39067135 1.05236168 0.95496651 0.21736805
 0.70576706 2.07862167 0.13456735 0.94106121 0.31561565 0.84381792
 0.3716493 ]


In [ ]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

In [ ]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [ ]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [ ]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

In [ ]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

In [ ]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)