# NumPy

numpy is python's package for doing math that is more advanced than +-*/

This includes special functions like cosine, exponential, sqrt, ...

On top of this we can use numpy to generate samples from many types of random variables

numpy also has a powerful data type to define vectors, matrices, and tensors

With these data types numpy also allows us to do linear algebra - matrix multiplication and matrix-vector solutions

In [1]:
# the first step of using numpy is to tell python to use it
import numpy as np

In [2]:
print(np.cos(np.pi))
print(np.sqrt(1.21))
print(np.log(np.exp(5.2)))

-1.0
1.1
5.2


In [3]:
# we can create numpy arrays by converting lists
# this is a vector
vec = np.array([1,2,3])
print(vec)
# we can create matrices by converting lists of lists
mat = np.array([[1,2,1],[4,5,9],[1,8,9]])
print('')
print(mat)
print('')
print(mat.T)

[1 2 3]

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[[1 4 1]
 [2 5 8]
 [1 9 9]]


In [4]:
# there are lots of other ways to create numpy arrays
vec2 = np.arange(0,15)
print(vec2)
print('')
vec3 = np.arange(3,21,6)
print(vec3)


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]

[ 3  9 15]


In [5]:

vec4 = np.linspace(0,5,10)
print(vec4)
print('')
print(vec4.reshape(5,2))
vec4_reshaped = vec4.reshape(5,2)
print(vec4_reshaped)
print(vec4)

[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]

[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[[0.         0.55555556]
 [1.11111111 1.66666667]
 [2.22222222 2.77777778]
 [3.33333333 3.88888889]
 [4.44444444 5.        ]]
[0.         0.55555556 1.11111111 1.66666667 2.22222222 2.77777778
 3.33333333 3.88888889 4.44444444 5.        ]


In [6]:
mat2 = np.zeros([5,3])
print(mat2)
mat3 = np.ones((3,5))
print('')
print(mat3)
mat4 = np.eye(5)
print('')
print(mat4)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [7]:
# we can +-*/ arrays together if they're the right size
vec5 = np.arange(1,6)
vec6 = np.arange(3,8)
print(vec5)
print(vec6)
print(vec5+vec6)
print(vec5*vec6)
print(1/vec5)
print(np.sqrt(vec6))

[1 2 3 4 5]
[3 4 5 6 7]
[ 4  6  8 10 12]
[ 3  8 15 24 35]
[1.         0.5        0.33333333 0.25       0.2       ]
[1.73205081 2.         2.23606798 2.44948974 2.64575131]


In [8]:
# we can do matrix multiplication
print(mat)
print('')
print(vec)
print()
product = np.matmul(mat,vec)
print(product)

[[1 2 1]
 [4 5 9]
 [1 8 9]]

[1 2 3]

[ 8 41 44]


In [9]:
print(np.linalg.solve(mat,product))
print('')
print(np.linalg.inv(mat))

[1. 2. 3.]

[[ 0.5         0.18518519 -0.24074074]
 [ 0.5        -0.14814815  0.09259259]
 [-0.5         0.11111111  0.05555556]]


In [10]:
# we can find the unique values in an array
vec7 = np.array(['blue','red','orange','purple','purple','orange','Red',6])
print(vec7)
print(np.unique(vec7))

['blue' 'red' 'orange' 'purple' 'purple' 'orange' 'Red' '6']
['6' 'Red' 'blue' 'orange' 'purple' 'red']


In [11]:
# we can also use numpy to generate samples of a random variable
rand_mat = np.random.rand(5,5) # uniform random variable
print(rand_mat)
rand_mat2 = np.random.randn(10,5) # standard normal random variable
print('')
print(rand_mat2)

[[0.83059537 0.12666685 0.1196991  0.99406731 0.52583655]
 [0.72634856 0.1605605  0.21610877 0.1180551  0.80609238]
 [0.54732923 0.65839349 0.98003778 0.40722124 0.06625722]
 [0.84201423 0.57696628 0.73730935 0.74917778 0.35955217]
 [0.40651619 0.28411825 0.08367409 0.04887732 0.16738089]]

[[-0.83404353 -0.02352917 -0.70687553 -0.06439323  0.79748248]
 [ 0.25191872 -0.02172114  0.54988366 -1.19072618  0.06151818]
 [-0.56871168 -0.45973984 -0.69417228 -0.91221709  1.98357282]
 [-0.25427228  1.35615765  0.19621822 -1.18168657 -0.08240062]
 [ 0.72797836 -2.3833607   1.12541374 -0.46534616 -0.99710864]
 [-0.86305669  0.88564287  0.26260307  0.83589873  0.31750389]
 [ 0.59630382 -0.61711844  0.40535625 -1.05084538 -0.78281654]
 [-0.05411213  1.33260329 -0.27961213  0.74612601 -0.32486929]
 [-1.41570873  0.3110597   2.20681936 -0.64093171 -0.01702433]
 [ 0.0140522   1.1996399  -1.17640013 -0.14685086  1.16916937]]


In [12]:
# we can also use numpy for statistical tools on arrays
print(np.mean(rand_mat))
print(np.std(rand_mat2))

0.4615542400789372
0.9005964009142994


In [13]:
print(np.min(rand_mat))
print(np.max(rand_mat2))

0.04887732111344878
2.2068193587239393


In [14]:
# break here for next video!

In [15]:
# how do we access entries in a numpy vector
rand_vec = np.random.randn(19)
print(rand_vec)
print(rand_vec[6])

[ 1.24466342 -0.05175066  0.59064507  0.05026384  0.37560707 -0.70510198
 -0.44727676  1.91620867 -0.28764887  0.26080504 -0.62590064  1.64958164
  0.08423595  0.43315862 -0.9953902   0.30019598  1.31272033  0.07285763
  1.0133767 ]
-0.44727675673571277


In [16]:
# we can access multiple entries at once using :
print(rand_vec[4:9])

[ 0.37560707 -0.70510198 -0.44727676  1.91620867 -0.28764887]


In [17]:
# we can also access multiple non-consecutive entries using np.arange
print(np.arange(0,15,3))
print(rand_vec[np.arange(0,15,3)])

[ 0  3  6  9 12]
[ 1.24466342  0.05026384 -0.44727676  0.26080504  0.08423595]


In [18]:
# what about matrices
print(rand_mat)
print(rand_mat[1][2])
print(rand_mat[1,2])


[[0.83059537 0.12666685 0.1196991  0.99406731 0.52583655]
 [0.72634856 0.1605605  0.21610877 0.1180551  0.80609238]
 [0.54732923 0.65839349 0.98003778 0.40722124 0.06625722]
 [0.84201423 0.57696628 0.73730935 0.74917778 0.35955217]
 [0.40651619 0.28411825 0.08367409 0.04887732 0.16738089]]
0.21610876621185326
0.21610876621185326


In [19]:
print(rand_mat[0:2,1:3])

[[0.12666685 0.1196991 ]
 [0.1605605  0.21610877]]


In [20]:
# let's change some values in an array!
print(rand_vec)
rand_vec[3:5] = 4
print('')
print(rand_vec)
rand_vec[3:5] = [1,2]
print('')
print(rand_vec)

[ 1.24466342 -0.05175066  0.59064507  0.05026384  0.37560707 -0.70510198
 -0.44727676  1.91620867 -0.28764887  0.26080504 -0.62590064  1.64958164
  0.08423595  0.43315862 -0.9953902   0.30019598  1.31272033  0.07285763
  1.0133767 ]

[ 1.24466342 -0.05175066  0.59064507  4.          4.         -0.70510198
 -0.44727676  1.91620867 -0.28764887  0.26080504 -0.62590064  1.64958164
  0.08423595  0.43315862 -0.9953902   0.30019598  1.31272033  0.07285763
  1.0133767 ]

[ 1.24466342 -0.05175066  0.59064507  1.          2.         -0.70510198
 -0.44727676  1.91620867 -0.28764887  0.26080504 -0.62590064  1.64958164
  0.08423595  0.43315862 -0.9953902   0.30019598  1.31272033  0.07285763
  1.0133767 ]


In [21]:
print(rand_mat)
rand_mat[1:3,3:5] = 0
print('')
print(rand_mat)

[[0.83059537 0.12666685 0.1196991  0.99406731 0.52583655]
 [0.72634856 0.1605605  0.21610877 0.1180551  0.80609238]
 [0.54732923 0.65839349 0.98003778 0.40722124 0.06625722]
 [0.84201423 0.57696628 0.73730935 0.74917778 0.35955217]
 [0.40651619 0.28411825 0.08367409 0.04887732 0.16738089]]

[[0.83059537 0.12666685 0.1196991  0.99406731 0.52583655]
 [0.72634856 0.1605605  0.21610877 0.         0.        ]
 [0.54732923 0.65839349 0.98003778 0.         0.        ]
 [0.84201423 0.57696628 0.73730935 0.74917778 0.35955217]
 [0.40651619 0.28411825 0.08367409 0.04887732 0.16738089]]


In [22]:
sub_mat = rand_mat[0:2,0:3]
print(sub_mat)
sub_mat[:] = 3
print(sub_mat)


[[0.83059537 0.12666685 0.1196991 ]
 [0.72634856 0.1605605  0.21610877]]
[[3. 3. 3.]
 [3. 3. 3.]]


In [23]:
print(rand_mat)

[[3.         3.         3.         0.99406731 0.52583655]
 [3.         3.         3.         0.         0.        ]
 [0.54732923 0.65839349 0.98003778 0.         0.        ]
 [0.84201423 0.57696628 0.73730935 0.74917778 0.35955217]
 [0.40651619 0.28411825 0.08367409 0.04887732 0.16738089]]


In [24]:
sub_mat2 = rand_mat[0:2,0:3].copy()
sub_mat2[:] = 99
print(sub_mat2)
print(rand_mat)


[[99. 99. 99.]
 [99. 99. 99.]]
[[3.         3.         3.         0.99406731 0.52583655]
 [3.         3.         3.         0.         0.        ]
 [0.54732923 0.65839349 0.98003778 0.         0.        ]
 [0.84201423 0.57696628 0.73730935 0.74917778 0.35955217]
 [0.40651619 0.28411825 0.08367409 0.04887732 0.16738089]]


In [25]:
# break here for next video

In [26]:
# we can also access entries with logicals
rand_vec = np.random.randn(15)

print(rand_vec)
print(rand_vec>0)
print(rand_vec[rand_vec>0])

[-0.94262519  0.66677871 -0.23818523  0.86558486 -0.73625392 -1.02315632
 -0.02788809 -0.3772447   0.0143068  -1.33347044 -0.23538894 -0.07564612
  0.47434641  0.83389878  0.02243637]
[False  True False  True False False False False  True False False False
  True  True  True]
[0.66677871 0.86558486 0.0143068  0.47434641 0.83389878 0.02243637]


In [27]:
print(rand_mat2)
print(rand_mat2[rand_mat2>0])

[[-0.83404353 -0.02352917 -0.70687553 -0.06439323  0.79748248]
 [ 0.25191872 -0.02172114  0.54988366 -1.19072618  0.06151818]
 [-0.56871168 -0.45973984 -0.69417228 -0.91221709  1.98357282]
 [-0.25427228  1.35615765  0.19621822 -1.18168657 -0.08240062]
 [ 0.72797836 -2.3833607   1.12541374 -0.46534616 -0.99710864]
 [-0.86305669  0.88564287  0.26260307  0.83589873  0.31750389]
 [ 0.59630382 -0.61711844  0.40535625 -1.05084538 -0.78281654]
 [-0.05411213  1.33260329 -0.27961213  0.74612601 -0.32486929]
 [-1.41570873  0.3110597   2.20681936 -0.64093171 -0.01702433]
 [ 0.0140522   1.1996399  -1.17640013 -0.14685086  1.16916937]]
[0.79748248 0.25191872 0.54988366 0.06151818 1.98357282 1.35615765
 0.19621822 0.72797836 1.12541374 0.88564287 0.26260307 0.83589873
 0.31750389 0.59630382 0.40535625 1.33260329 0.74612601 0.3110597
 2.20681936 0.0140522  1.1996399  1.16916937]


In [28]:

print(rand_vec)
print('')
rand_vec[rand_vec>0.5] = -5
print(rand_vec)

[-0.94262519  0.66677871 -0.23818523  0.86558486 -0.73625392 -1.02315632
 -0.02788809 -0.3772447   0.0143068  -1.33347044 -0.23538894 -0.07564612
  0.47434641  0.83389878  0.02243637]

[-0.94262519 -5.         -0.23818523 -5.         -0.73625392 -1.02315632
 -0.02788809 -0.3772447   0.0143068  -1.33347044 -0.23538894 -0.07564612
  0.47434641 -5.          0.02243637]


In [29]:
# let's save some arrays on the disk for use later!
np.save('saved_file_name',rand_mat2)


In [30]:
np.savez('zipped_file_name',rand_mat=rand_mat,rand_mat2=rand_mat2)

In [31]:
# now let's load it
loaded_vec = np.load('saved_file_name.npy')
loaded_zip = np.load('zipped_file_name.npz')

print(loaded_vec)
print('')
print(loaded_zip)

[[-0.83404353 -0.02352917 -0.70687553 -0.06439323  0.79748248]
 [ 0.25191872 -0.02172114  0.54988366 -1.19072618  0.06151818]
 [-0.56871168 -0.45973984 -0.69417228 -0.91221709  1.98357282]
 [-0.25427228  1.35615765  0.19621822 -1.18168657 -0.08240062]
 [ 0.72797836 -2.3833607   1.12541374 -0.46534616 -0.99710864]
 [-0.86305669  0.88564287  0.26260307  0.83589873  0.31750389]
 [ 0.59630382 -0.61711844  0.40535625 -1.05084538 -0.78281654]
 [-0.05411213  1.33260329 -0.27961213  0.74612601 -0.32486929]
 [-1.41570873  0.3110597   2.20681936 -0.64093171 -0.01702433]
 [ 0.0140522   1.1996399  -1.17640013 -0.14685086  1.16916937]]



In [32]:
print(loaded_zip['rand_mat'])
print('')
print(loaded_zip['rand_mat2'])

new_array  = loaded_zip['rand_mat']
print(new_array)

[[3.         3.         3.         0.99406731 0.52583655]
 [3.         3.         3.         0.         0.        ]
 [0.54732923 0.65839349 0.98003778 0.         0.        ]
 [0.84201423 0.57696628 0.73730935 0.74917778 0.35955217]
 [0.40651619 0.28411825 0.08367409 0.04887732 0.16738089]]

[[-0.83404353 -0.02352917 -0.70687553 -0.06439323  0.79748248]
 [ 0.25191872 -0.02172114  0.54988366 -1.19072618  0.06151818]
 [-0.56871168 -0.45973984 -0.69417228 -0.91221709  1.98357282]
 [-0.25427228  1.35615765  0.19621822 -1.18168657 -0.08240062]
 [ 0.72797836 -2.3833607   1.12541374 -0.46534616 -0.99710864]
 [-0.86305669  0.88564287  0.26260307  0.83589873  0.31750389]
 [ 0.59630382 -0.61711844  0.40535625 -1.05084538 -0.78281654]
 [-0.05411213  1.33260329 -0.27961213  0.74612601 -0.32486929]
 [-1.41570873  0.3110597   2.20681936 -0.64093171 -0.01702433]
 [ 0.0140522   1.1996399  -1.17640013 -0.14685086  1.16916937]]
[[3.         3.         3.         0.99406731 0.52583655]
 [3.         3.    

In [33]:
# we can also save/load as text files...but only single variables
np.savetxt('text_file_name.txt',rand_mat,delimiter=',')
rand_mat_txt = np.loadtxt('text_file_name.txt',delimiter=',')
print(rand_mat)
print('')
print(rand_mat_txt)

[[3.         3.         3.         0.99406731 0.52583655]
 [3.         3.         3.         0.         0.        ]
 [0.54732923 0.65839349 0.98003778 0.         0.        ]
 [0.84201423 0.57696628 0.73730935 0.74917778 0.35955217]
 [0.40651619 0.28411825 0.08367409 0.04887732 0.16738089]]

[[3.         3.         3.         0.99406731 0.52583655]
 [3.         3.         3.         0.         0.        ]
 [0.54732923 0.65839349 0.98003778 0.         0.        ]
 [0.84201423 0.57696628 0.73730935 0.74917778 0.35955217]
 [0.40651619 0.28411825 0.08367409 0.04887732 0.16738089]]
